services:

  kuru-api:
    build: .
    image: kuru-backend:local
    container_name: kuru-api
    restart: unless-stopped
    volumes:
      - kuru-data:/app/data
    env_file:
      - .env.prod

  kuru-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: kuru-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    env_file:
      - .env.prod
    depends_on:
      - kuru-api

volumes:
  kuru-data:
