spring:
  application:
    name: kuru
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:sqlite:${KURU_SQLITE_FILE:data/kuru.db}
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 5
      connection-init-sql: "PRAGMA foreign_keys = ON; PRAGMA journal_mode = WAL;"

  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: true
    clean-on-validation-error: false
    baseline-version: 0
    locations: classpath:db/migration

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  kuru:
    storage:
      endpoint: ${STORAGE_ENDPOINT:http://localhost:9000}
      access-key: ${STORAGE_ACCESS_KEY:minio}
      secret-key: ${STORAGE_SECRET_KEY:minioadmin}
      path-style-access: ${STORAGE_PATH_STYLE:true}
      bucket: ${STORAGE_BUCKET:kuru-bucket}

  server:
    port: ${PORT:8080}